[project]
name = "saga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KAMEHAMEHA-05", email = "imsawant05@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
saga = "saga:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
